# Generated by Django 4.1.7 on 2023-12-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="images/default_pp.jpg",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
