# Generated by Django 4.2.10 on 2024-03-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="images/default_pp.png",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
