# Generated by Django 4.2.10 on 2024-03-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile", name="activity", field=models.JSONField(default=list),
        ),
    ]
