# Generated by Django 4.2.10 on 2024-03-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_text", models.CharField(max_length=500)),
                ("output_text", models.CharField(max_length=500)),
            ],
        ),
    ]
