# Generated by Django 4.2.10 on 2024-03-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="output_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
