# Generated by Django 4.2.10 on 2024-03-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_deck_created_by_deck_users_flashcard_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="deck", name="flashcards",),
        migrations.AddField(
            model_name="flashcard",
            name="decks",
            field=models.ManyToManyField(related_name="flashcards", to="mainapp.deck"),
        ),
    ]
