# Generated by Django 4.2.10 on 2024-03-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_remove_deck_flashcards_flashcard_decks"),
    ]

    operations = [
        migrations.RenameField(model_name="deck", old_name="users", new_name="user",),
    ]
