# Generated by Django 4.2.10 on 2024-03-07 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_language_alter_deck_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="from_language",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="translation_from",
                to="mainapp.language",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="translation",
            name="to_language",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="translation_to",
                to="mainapp.language",
            ),
            preserve_default=False,
        ),
    ]
