# Generated by Django 4.2.10 on 2024-03-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_translation_from_language_translation_to_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language", name="symbol", field=models.CharField(max_length=4),
        ),
    ]
