# Generated by Django 4.2.10 on 2024-03-07 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_alter_language_symbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="from_language",
            field=models.ForeignKey(
                default=70,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="translation_from",
                to="mainapp.language",
            ),
        ),
    ]
