# Generated by Django 4.2.10 on 2024-03-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0010_alter_translation_from_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
