# Generated by Django 4.2.10 on 2024-03-09 18:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0011_deck_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="deck", name="created_by",),
        migrations.RemoveField(model_name="flashcard", name="decks",),
        migrations.AddField(
            model_name="flashcard",
            name="deck",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcards",
                to="mainapp.deck",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flashcard",
            name="easiness_factor",
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="interval",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="next_review",
            field=models.DateField(default=datetime.date(2024, 3, 9)),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="winning_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(model_name="deck", name="user",),
        migrations.AddField(
            model_name="deck",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decks",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
