# Generated by Django 4.2.10 on 2024-03-09 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0013_alter_flashcard_deck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="deck",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcards",
                to="mainapp.deck",
            ),
            preserve_default=False,
        ),
    ]
