# Generated by Django 4.2.10 on 2024-03-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0015_flashcard_last_review_flashcard_number_of_agains_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcard",
            name="total_time",
            field=models.FloatField(default=0),
        ),
    ]
