# Generated by Django 4.2.10 on 2024-03-27 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0016_flashcard_total_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="next_review",
            field=models.DateField(default=datetime.date(2024, 3, 27)),
        ),
    ]
