# Generated by Django 4.2.10 on 2024-03-29 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0017_alter_flashcard_next_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="next_review",
            field=models.DateField(default=datetime.date(2024, 3, 29)),
        ),
    ]
