# Generated by Django 4.2.10 on 2024-04-17 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0020_flashcard_from_language_flashcard_to_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="alpha2_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="next_review",
            field=models.DateField(default=datetime.date(2024, 4, 17)),
        ),
    ]
