# Generated by Django 4.2.10 on 2024-04-21 08:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0021_language_alpha2_code_alter_flashcard_next_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="next_review",
            field=models.DateField(default=datetime.date(2024, 4, 21)),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
