# Generated by Django 4.2.10 on 2024-05-31 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_alter_flashcard_next_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='next_review',
            field=models.DateField(default=datetime.date(2024, 5, 31)),
        ),
    ]
