from django.core.management.base import BaseCommand
from mainapp.utils import create_language_objects

class Command(BaseCommand):
    help="Creates languages object based on a list of dictionaries with keys 'name' and 'symbol'."

    def handle(self, *args, **kwargs):
        language_list = [{"name": "english", "symbol": "en"},
{"name": "chinese", "symbol": "zh"},
{"name": "arabic", "symbol": "ar"},
{"name": "russian", "symbol": "ru"},
{"name": "french", "symbol": "fr"},
{"name": "german", "symbol": "de"},
{"name": "spanish", "symbol": "es"},
{"name": "portuguese", "symbol": "pt"},
{"name": "italian", "symbol": "it"},
{"name": "japanese", "symbol": "ja"},
{"name": "korean", "symbol": "ko"},
{"name": "greek", "symbol": "el"},
{"name": "dutch", "symbol": "nl"},
{"name": "hindi", "symbol": "hi"},
{"name": "turkish", "symbol": "tr"},
{"name": "malay", "symbol": "ms"},
{"name": "thai", "symbol": "th"},
{"name": "vietnamese", "symbol": "vi"},
{"name": "indonesian", "symbol": "id"},
{"name": "hebrew", "symbol": "he"},
{"name": "polish", "symbol": "pl"},
{"name": "mongolian", "symbol": "mn"},
{"name": "czech", "symbol": "cs"},
{"name": "hungarian", "symbol": "hu"},
{"name": "estonian", "symbol": "et"},
{"name": "bulgarian", "symbol": "bg"},
{"name": "danish", "symbol": "da"},
{"name": "finnish", "symbol": "fi"},
{"name": "romanian", "symbol": "ro"},
{"name": "swedish", "symbol": "sv"},
{"name": "slovenian", "symbol": "sl"},
{"name": "persian/farsi", "symbol": "fa"},
{"name": "bosnian", "symbol": "bs"},
{"name": "serbian", "symbol": "sr"},
{"name": "fijian", "symbol": "fj"},
{"name": "filipino", "symbol": "tl"},
{"name": "haitiancreole", "symbol": "ht"},
{"name": "catalan", "symbol": "ca"},
{"name": "croatian", "symbol": "hr"},
{"name": "latvian", "symbol": "lv"},
{"name": "lithuanian", "symbol": "lt"},
{"name": "urdu", "symbol": "ur"},
{"name": "ukrainian", "symbol": "uk"},
{"name": "welsh", "symbol": "cy"},
{"name": "tahiti", "symbol": "ty"},
{"name": "tongan", "symbol": "to"},
{"name": "swahili", "symbol": "sw"},
{"name": "samoan", "symbol": "sm"},
{"name": "slovak", "symbol": "sk"},
{"name": "afrikaans", "symbol": "af"},
{"name": "norwegian", "symbol": "no"},
{"name": "bengali", "symbol": "bn"},
{"name": "malagasy", "symbol": "mg"},
{"name": "maltese", "symbol": "mt"},
{"name": "queretaro otomi", "symbol": "otq"},
{"name": "klingon/tlhingan hol", "symbol": "tlh"},
{"name": "gujarati", "symbol": "gu"},
{"name": "tamil", "symbol": "ta"},
{"name": "telugu", "symbol": "te"},
{"name": "punjabi", "symbol": "pa"},
{"name": "amharic", "symbol": "am"},
{"name": "azerbaijani", "symbol": "az"},
{"name": "bashkir", "symbol": "ba"},
{"name": "belarusian", "symbol": "be"},
{"name": "cebuano", "symbol": "ceb"},
{"name": "chuvash", "symbol": "cv"},
{"name": "esperanto", "symbol": "eo"},
{"name": "basque", "symbol": "eu"},
{"name": "irish", "symbol": "ga"}]

        create_language_objects(language_list)
        self.stdout.write(self.style.SUCCESS('Successfully created Language objects'))